### PR TITLE
make mwdust possible to be compiled on Windows

### LINKED ISSUE #17: Dust Map Installation Not Working
I am a second-year undergraduate currently working on a project that involves the installation of the mwdust package.  The installation commands are intended for Unix, yet I am trying to run them on a Windows machine.  When I run setup.py, I get the following error message: "FileNotFoundError: [WinError 2] The system cannot find the file specified".  Is there another way to install mwdust?

### PR DESCRIPTION
**Pull request by henrysky**
This PR adds the following to `mwdust`

1. `mwdust` can now be compiled on windows, so the SFD C code run on Windows. This will partially fix #17, #19 
2. Ctrl+C can now terminate SFD code when running with a large array of coordinates
3. Progress bar in SFD code

Keep the PR open for now, I haven't tested whether SFD code return the correct result on Windows (but at least the code runs). I will finish up the PR and test later as I am mostly running `mwdust` on linux now.

### CODE REVIEW

**Comment by henrysky** [comment]
I have reverted the auto-formatted code last night and Mac and Linux builds seems to be passing now.

Although SFD code is running on Windows, doing something like `sfd(30., 3., 1.)` returns different result on Windows and Linux. Windows returns `array([2.46522093])` while Linux returns `array([2.60820293])`. 

Interestingly, many others coordinates returns the same result on Windows and Linux, for example offsetting the coordinates a bit `sfd(30.01, 3.01, 1.)` returns `array([2.63929105])` on both Windows and Linux.

**Comment by jobovy** [comment]
> Although SFD code is running on Windows, doing something like `sfd(30., 3., 1.)` returns different result on Windows and Linux. Windows returns `array([2.46522093])` while Linux returns `array([2.60820293])`.
> 
> Interestingly, many others coordinates returns the same result on Windows and Linux, for example offsetting the coordinates a bit `sfd(30.01, 3.01, 1.)` returns `array([2.63929105])` on both Windows and Linux.

This is strange, but I wonder this is just because of the interpolation that the SFD does working slightly differently on Windows for some reason? The range of extinction that's interpolated over in this area is pretty large, e.g., put `30. 3. gal` in [this website](https://irsa.ipac.caltech.edu/applications/DUST/) and it shows you that the extinction within 5 arcmin varies between 2.4296 and 2.8331. 

Maybe you can try without the interpolation? Like
```
from mwdust import SFD
sfd= SFD(interp=False)
sfd(30., 3., 1.)
```
I get `array([2.56323576])` without interpolation.

**Comment by henrysky** [comment]
> I get `array([2.56323576])` without interpolation.

Indeed I can confirm I also get `array([2.56323576])` on Windows too without interpolation.

Also to let you know that I get other hierarchical dust maps to work on Windows too. I have yet to implement all healpix functions used by mwdust but the main ones required to get extinction are implemented now in C code within mwdust and seems to work correctly on Windows with trying a few set of coordinates.

I think I will wait this PR to be merged first since the healpix is another issue.

**Comment by jobovy** [comment]
Okay, so this is ready for review then?

**Comment by henrysky** [comment]
> Okay, so this is ready for review then?

yes

**Comment by jobovy** [comment]
Okay, I added some SFD tests in `main` and merged them here and they now pass here in Windows as well 🎉 🎉 ! Will merge, thanks for figuring this out!

**Pull request merged**
