### PR TITLE
Added Bayestar 17 and 19 and made a new combined map that will also be downloaded

### PR DESCRIPTION
**Pull request by jan-rybizki**
I have not yet changed the Readme.rst
I also did not look at the new maps yet.
But Bayestar format stayed the same. Only in 2017 the healpix resolution increased in specific areas of the sky and for Bayestar 19 the distance grid got finer.

### CODE REVIEW

**Comment by jobovy** [comment]
Hi @jan-rybizki,

Finally started looking at this, so far looks good, but I want to do some more tests before merging. Fe questions for now:
* I notice that you didn't include a Combined17 map. Is that because you think there is no use for this given that ``Green19`` is out? Could be useful for analyzing the difference between different versions of Bayestar
* Is the MPG URL for the new combined dust map long term stable? I put the original combined map on zenodo, which should be long term stable.

**Comment by jan-rybizki** [comment]
Hey @jobovy 
I did not create a Combined17map because I thought 19 is enough. But you could of course do it. In fact for GDR3mock I am using a combination of Bayestar17 and 19. Because out of the plane 17 looks smoother.
The MPG URL is at least as long term stable as I am still employed at MPG. So might not be on a 5 year baseline. I should actually ask if that's true. Maybe you should put it somewhere else then.

**Comment by jobovy** [comment]
Okay thanks. To-do list for merging this PR:
- [ ] Put new combined map on zenodo and switch to that URL
- [ ] Make default installation downloads only essential ones (combined maps, latest Green, Marshall, Drimmel, SFD?) and have ``--all-downloads`` option to download all
- [ ] Implement map plotting function for HEALPIx-based maps (I have code to do this)

**Comment by jobovy** [comment]
I've edited the README and implemented the additional improvements in downloading and plotting that I suggested above, so all looks good now and I will merge. I will also release a new version on PyPI. Thanks again @jan-rybizki for this very useful addition!

**Pull request merged**
